plt.figure(figsize=(10, 5))
        plt.plot(lags, autocorr_values, label=f'Autocorrelation of {param}')
        plt.xlabel('Lag')
        plt.ylabel('Autocorrelation')
        plt.title(f'Autocorrelation Plot for {param}')
        plt.ylim(-0.5, 0.5)
        plt.legend()
        plt.grid(True)
        plt.savefig(f'{SBIConfig.PLOT_PATH}SBI_{model_type}_{param}_autocorrelation_plot.png')
        plt.close()